#!/bin/bash
_aws()
{
  echo "aws - $action: $provider@$profile"
  command="export AWS_PROFILE=$profile"
  _executeCommand
}

_gcp()
{
  echo "gcp - $action $provider@$profile"
  command="gcloud config configurations activate $profile"
  _executeCommand
}

_kubectl()
{
  echo "kubectl - $action $provider@$profile"
  command="kubectx $profile"
  _executeCommand
}

_az()
{
  echo "az - $action $provider@$profile"
  profile=$(echo $profile|awk -F% '{print $1}')
  prof=$(echo $profile|awk '{gsub("_"," "); print $0}')
  echo "new profile: $profile"
  echo "new prof: $prof"
  subscription_id=$(az account list --all --output table | awk -F"\t" -v pr="$prof" '$1==pr{print $3}')
  echo "subscription_id: $subscription_id"
  command="az account set $subscription_id"
  #_executeCommand
}

_executeCommand()
{
  $command
  echo "Executing: "$command  
}

_setEnvVariables()
{
  setBoboProfile="export BOBO_PROFILE=$profile"
  setBoboProvider="export BOBO_PROVIDER=$provider"
  $setBoboProfile
  $setBoboProvider
  setPrompt="export PS1=\u@\h:\w\e[31m($provider-$profile)\e[m>"
  $setPrompt
}

provider=$1
action=$2
profile=$3

if [ $# -ne 3 ]; then
    echo "Wrong params"
    exit 1
fi

case "${provider}" in
  "aws" )
    _aws
    ;;
  "gcp" )
    _gcp
    ;;
  "kubectl" )
    _kubectl
    ;;
  "az" )
    _az
    ;;
esac
_setEnvVariables


